name: 'Merge Flow'

on: pull_request_target

jobs:
  npm-test:
    name: npm test
    runs-on: macos-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - run: npm install
        - run: npm test
