name: 'Success/Fail'

on: push

jobs:
  success-fail:
    name: Test on merge to master
    runs-on: macos-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Success
          run: |
            chmod +x ./.github/workflows/success-or-fail.sh
            ./.github/workflows/success-or-fail.sh
